<template>
  <div id="app">
    <header>
        <img v-bind:src="data.logo" alt="pic">
        <div id="msg">
            <p>配送时间约45分钟</p>
            <p>公告: {{data.notice}}</p>
        </div>
        <div id="atention" v-on:click='payattention'>{{atention}}</div>
    </header>
    <div class="nav">
      <router-link to="/" >菜单</router-link>
      <router-link to="/comment" >评价</router-link>
      <router-link to="/merch" >商家</router-link>
    </div>
    <router-view  v-if="data&&data.products.length>0"
      v-bind:productData='data.products' 
      v-bind:commentsData='data.comments'
      v-bind:merchData='data'
    />
  </div>
</template>
<script>
export default {
  name: 'app',
  data() {
    return {
      data:database,
      atention:'关注',
    }  
  },
  created() { 
    console.log(this.data);
    console.log(this);
    this.senmsg();
  }, 
  methods: {
      payattention:function() {
          this.atention=='关注' ? this.atention='已关注':this.atention='关注';
      },
      senmsg: function() {
          this.$store.commit('getmsg',[this.data.delivery_start_price, this.data.deliver_fee])
      }
  }, 

} 
var database = {
    "sid":144751338682661120,
    "name":"山下炊私房菜（文三店）",
    "logo":"https://p0.meituan.net/120.0/waimaipoi/078cad5e23b0b280cca28548f11e8f18188084.jpg",
    "address":"文三路455号",
    "notice": "欢迎光临",
    "latitude":30.276568,
    "longitude":120.12707,
    "opening_hours":"09:30-21:00",
    "phone":"18806523117/13858189054",
    "avg_delivery_duration":40,
    "score":4.2,
    "delivery_start_price":20, //起送价
    "deliver_fee":2, //配送费
    "is_premium":"否",
    "comments":[
        {
            "author":{
                "name":"葛***5",
                "aid":"89019462",
                "avatar":"https://img.meituan.net/avatar/74fa9c841f963bf22a99549ac51f56d635409.jpg"
            },
            "comment":{
                "total_score":"4",
                "detail":"#酱爆肉沫茄子（不含米饭）##家常肉饼蒸蛋（不含米饭）##高庄馒头（一份两个）#不错，#农家小炒肉（不含米饭）#这哪是农家小炒肉啊，这明明是尖椒炒肉，而且是鸡肉，分类不够",
                "publish_time":"1543539619",
                "shop_reply":""
            }
        },
        {
            "author":{
                "name":"匿***户",
                "aid":"0",
                "avatar":""
            },
            "comment":{
                "total_score":"4",
                "detail":"以为下雨天配送会慢，结果下单15分钟后外卖小哥就到了，我还在地铁里…冲这速度，我以后还会点这家外卖。白斩鸡很不错，非常嫩，调味也好，不愧是招牌，就是汁给多了，底部的太咸。两个素菜都还行，手撕包菜感觉炒的时候像加了水，味道差一些。算上满减，非常实惠。",
                "publish_time":"1543539619",
                "shop_reply":"感谢您的惠顾和认可，我们会一如既往的 保持良好的服务品质，期待再次光临！"
            }
        },
        {
            "author":{
                "name":"p***8",
                "aid":"10743056",
                "avatar":"https://img.meituan.net/avatar/8c18a0a0417c51bf1cc0083bb337b49323446.jpg"
            },
            "comment":{
                "total_score":"5",
                "detail":"#农家小炒肉（不含米饭）##尖椒豆腐皮（不含米饭）#味道很正，符合我的胃口",
                "publish_time":"1543539619",
                "shop_reply":""
            }
        },
        {
            "author":{
                "name":"O***1",
                "aid":"411214452",
                "avatar":"https://img.meituan.net/avatar/cdfaa946eb1c10e0022677f77b8c2afa31289.jpg"
            },
            "comment":{
                "total_score":"5",
                "detail":"其实…本意就是不要米饭。但是商家还是送了…谢谢~",
                "publish_time":"1543539619",
                "shop_reply":""
            }
        },
        {
            "author":{
                "name":"柳***宗",
                "aid":"139574037",
                "avatar":"https://img.meituan.net/avatar/32c9aac8dd60111b1a5bb44387bd6ea112944.jpg"
            },
            "comment":{
                "total_score":"5",
                "detail":"挺好的，茄子很好吃，下回吃他家的啤酒鸭，很便宜",
                "publish_time":"1543539619",
                "shop_reply":"感谢您的惠顾和认可，我们会一如既往的 保持良好的服务品质，期待再次光临！"
            }
        },
        {
            "author":{
                "name":"A***0",
                "aid":"41169314",
                "avatar":""
            },
            "comment":{
                "total_score":"3",
                "detail":"外卖都是只有别家一半的量，关键是味道也不怎么样，花菜是满满一碗油，跑蛋切了一半，然后跟老很老",
                "publish_time":"1543539619",
                "shop_reply":"非常抱歉，没能给到好的用餐体验，我们会加强管理，保证良好的服务品质"
            }
        },
        {
            "author":{
                "name":"柳***宗",
                "aid":"139574037",
                "avatar":"https://img.meituan.net/avatar/32c9aac8dd60111b1a5bb44387bd6ea112944.jpg"
            },
            "comment":{
                "total_score":"5",
                "detail":"#醉香干锅啤酒鸭（不含米饭）##米饭（一份菜限购两份米饭）#啤酒鸭很好吃，而且很优惠，已经连续两天点这家了",
                "publish_time":"1543539619",
                "shop_reply":"感谢您的惠顾和认可，我们会一如既往的 保持良好的服务品质，期待再次光临！"
            }
        },
        {
            "author":{
                "name":"p***8",
                "aid":"10743056",
                "avatar":"https://img.meituan.net/avatar/8c18a0a0417c51bf1cc0083bb337b49323446.jpg"
            },
            "comment":{
                "total_score":"5",
                "detail":"#爆炒肥肠+手撕包菜+米饭一份#肥肠分量挺足的，价廉物美",
                "publish_time":"1543539619",
                "shop_reply":""
            }
        },
        {
            "author":{
                "name":"柳***宗",
                "aid":"139574037",
                "avatar":"https://img.meituan.net/avatar/32c9aac8dd60111b1a5bb44387bd6ea112944.jpg"
            },
            "comment":{
                "total_score":"5",
                "detail":"#香菇炒肉（不含米饭）##肉丝跑蛋（不含米饭）#今天吃的香菇烧肉，忘了跟老板说多放辣椒了。。。",
                "publish_time":"1543539619",
                "shop_reply":"感谢您的惠顾和认可，我们会一如既往的 保持良好的服务品质，期待再次光临！"
            }
        },
        {
            "author":{
                "name":"Y***7",
                "aid":"332852490",
                "avatar":""
            },
            "comment":{
                "total_score":"5",
                "detail":"菜品口感还不错?#鲜美的干锅茶树菇#",
                "publish_time":"1543539619",
                "shop_reply":"感谢您的惠顾和认可，我们会一如既往的 保持良好的服务品质，期待再次光临！"
            }
        },
        {
            "author":{
                "name":"匿***户",
                "aid":"0",
                "avatar":""
            },
            "comment":{
                "total_score":"3",
                "detail":"酸辣鸡胗感觉不太好，不酸也不辣。尖椒豆皮喜欢",
                "publish_time":"1543539619",
                "shop_reply":"感谢您的惠顾和认可，我们会一如既往的 保持良好的服务品质，期待再次光临！"
            }
        },
        {
            "author":{
                "name":"匿***户",
                "aid":"0",
                "avatar":""
            },
            "comment":{
                "total_score":"1",
                "detail":"#肉丝跑蛋（不含米饭）#不好吃#酸辣土豆丝（不含米饭）#没有酸味没有辣味下知道什么叫酸辣土豆丝",
                "publish_time":"1543539619",
                "shop_reply":"非常抱歉，没有能给到好的用餐体验，是我们工作疏忽，我们会加强后厨管理，提升服务质量。"
            }
        },
        {
            "author":{
                "name":"匿***户",
                "aid":"0",
                "avatar":""
            },
            "comment":{
                "total_score":"1",
                "detail":"馒头外湿内干，剩馒头热的，土豆片没有味，没有一点辣椒，盐放的也太少，当饭都没法吃，豆腐皮还行。",
                "publish_time":"1543539619",
                "shop_reply":"非常抱歉，没有能给到好的用餐体验，意见已经收到，我们会立马改进"
            }
        },
        {
            "author":{
                "name":"匿***户",
                "aid":"0",
                "avatar":""
            },
            "comment":{
                "total_score":"1",
                "detail":"这是菜吗？看了有食欲吗？饭那么少当我是蚂蚁啊，味道还那么恶心，我也是服了…香菇肉片竟然用干香菇，一股味道！你们这个店是怎么勇气能开啊，气饱了！第一次差评",
                "publish_time":"1543539619",
                "shop_reply":"非常抱歉，没有能给到好的用餐体验，我们会不断改进"
            }
        },
        {
            "author":{
                "name":"匿***户",
                "aid":"0",
                "avatar":""
            },
            "comment":{
                "total_score":"1",
                "detail":"一点油都没有，像是水煮的，然后味道也不好",
                "publish_time":"1543539619",
                "shop_reply":"非常抱歉，没有能给到好的用餐体验，是我们工作疏忽，我们会加强后厨管理，提升服务质量。"
            }
        },
        {
            "author":{
                "name":"匿***户",
                "aid":"0",
                "avatar":""
            },
            "comment":{
                "total_score":"2",
                "detail":"颜色太黑了，看着就没什么太大食欲了，不过，味道还凑合吧",
                "publish_time":"1543539619",
                "shop_reply":"非常抱歉，没能给到好的用餐体验，我们会不断改进品质"
            }
        }
    ],
    "products":[
        {
            "category":"主食（炒菜要单点哦）",
            "product":[
                {
                    "name":"米饭（一份菜限购两份米饭）",
                    "pid":"870064951",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/20e5b4457b8bb77a988e8a1d2d8282e4134358.jpg",
                    "price":"2",
                    "recommends_count":"96",
                    "sku_detail":[
                        {
                            "price":"2",
                            "sku_id":"944455936",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"高庄馒头（一份两个）",
                    "pid":"1007898231",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/92acf6dcbd385c7c9f9bec817d6e397486303.jpg",
                    "price":"3.66",
                    "recommends_count":"17",
                    "sku_detail":[
                        {
                            "price":"3.66",
                            "sku_id":"1108254894",
                            "sku":""
                        }
                    ]
                }
            ]
        },
        {
            "category":"山下炊拿手菜",
            "product":[
                {
                    "name":"肉丝跑蛋（不含米饭）",
                    "pid":"933364955",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/5c668f7500f6bbc8c40807a1e89c42c4159075.jpg",
                    "price":"13.88",
                    "recommends_count":"25",
                    "sku_detail":[
                        {
                            "price":"13.88",
                            "sku_id":"1014848271",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"红烧狮子头（不含米饭）",
                    "pid":"878783277",
                    "images":"https://p1.meituan.net/210.0/wmproductdwm/1ef488a69bb3097de3fac22284ff8f44591030.jpg",
                    "price":"15.88",
                    "recommends_count":"7",
                    "sku_detail":[
                        {
                            "price":"15.88",
                            "sku_id":"954034715",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"干锅有机花菜（不含米饭）",
                    "pid":"1023428272",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/8f9639dbc2c61a1ffcc555c67c262a2f182890.jpg",
                    "price":"18.88",
                    "recommends_count":"6",
                    "sku_detail":[
                        {
                            "price":"18.88",
                            "sku_id":"1126087305",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"香辣焖烧大鸡腿（不含米饭）",
                    "pid":"1204694130",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/cb3971e18a01d2743448dba6ab87efc7189878.jpg",
                    "price":"19.88",
                    "recommends_count":"4",
                    "sku_detail":[
                        {
                            "price":"19.88",
                            "sku_id":"1339760423",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"红烧带鱼（微辣，不含米饭）",
                    "pid":"1121110038",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/ef0c48a5a6c974fb9466d15b1e5fa1aa220047.jpg",
                    "price":"20.88",
                    "recommends_count":"1",
                    "sku_detail":[
                        {
                            "price":"20.88",
                            "sku_id":"1238615743",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"农家小炒肉（不含米饭）",
                    "pid":"870106389",
                    "images":"https://p0.meituan.net/210.0/wmproductdwm/8c165650ef06b013411cb914a761ef3e578499.jpg",
                    "price":"20.88",
                    "recommends_count":"6",
                    "sku_detail":[
                        {
                            "price":"20.88",
                            "sku_id":"944454455",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"经典鱼香肉丝（不含米饭）",
                    "pid":"1164515084",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/7c029c6eb579d069bda5da788d78b8d4224228.jpg",
                    "price":"21.88",
                    "recommends_count":"4",
                    "sku_detail":[
                        {
                            "price":"21.88",
                            "sku_id":"1291621611",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"爆炒辣鸡块（不含米饭）",
                    "pid":"1164692340",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/1e5874f32884ad89534e95b89328fb2b183455.jpg",
                    "price":"23.88",
                    "recommends_count":"1",
                    "sku_detail":[
                        {
                            "price":"23.88",
                            "sku_id":"1291807551",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"鲜美的干锅茶树菇",
                    "pid":"1212205817",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/cb75f8d4a748e6417fb6e2bd8641300b199282.jpg",
                    "price":"22.88",
                    "recommends_count":"2",
                    "sku_detail":[
                        {
                            "price":"22.88",
                            "sku_id":"1348334615",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"醉香干锅啤酒鸭（不含米饭）",
                    "pid":"1174790737",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/6e9c93b1a6929f0d7b839769d87de813176727.jpg",
                    "price":"22.88",
                    "recommends_count":"4",
                    "sku_detail":[
                        {
                            "price":"22.88",
                            "sku_id":"1303736169",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"江西特色酸辣鸡胗（不含米饭）",
                    "pid":"1034202747",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/6f9a0188411f47ae55fc7e43de6694b6177503.jpg",
                    "price":"23.88",
                    "recommends_count":"4",
                    "sku_detail":[
                        {
                            "price":"23.88",
                            "sku_id":"1138348311",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"红烧鸡翅尖（不含米饭）",
                    "pid":"1081611732",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/a2fdff6a2a3ca1c59cedec41835552fd191580.jpg",
                    "price":"26.88",
                    "recommends_count":"1",
                    "sku_detail":[
                        {
                            "price":"26.88",
                            "sku_id":"1191717329",
                            "sku":""
                        }
                    ]
                }
            ]
        },
        {
            "category":"实惠家常菜",
            "product":[
                {
                    "name":"尖椒豆腐皮（不含米饭）",
                    "pid":"1011795104",
                    "images":"https://p0.meituan.net/210.0/wmproductdwm/99d044eb4494ee4afeeb9178c9e4584d69818.jpg",
                    "price":"9.88",
                    "recommends_count":"22",
                    "sku_detail":[
                        {
                            "price":"9.88",
                            "sku_id":"1112779839",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"酸辣土豆丝（不含米饭）",
                    "pid":"870083353",
                    "images":"https://p0.meituan.net/210.0/wmproductdwm/00571ca54247fd794f4f3206ecf8e4ec574856.jpg",
                    "price":"11.88",
                    "recommends_count":"8",
                    "sku_detail":[
                        {
                            "price":"11.88",
                            "sku_id":"944464777",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"农家雪菜炖豆腐（不含米饭）",
                    "pid":"1087628161",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/a4dbd8f9da68cb5a1426fdd953b40d14142386.jpg",
                    "price":"13.88",
                    "recommends_count":"1",
                    "sku_detail":[
                        {
                            "price":"13.88",
                            "sku_id":"1198658327",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"清炒莴笋（不含米饭）",
                    "pid":"1212388192",
                    "images":"https://p1.meituan.net/210.0/wmproductdwm/65f847a6242cacc933aaa8fa8cfe26d8279241.jpg",
                    "price":"13.88",
                    "recommends_count":"4",
                    "sku_detail":[
                        {
                            "price":"13.88",
                            "sku_id":"1348635731",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"番茄炒鸡蛋（不含米饭）",
                    "pid":"870560310",
                    "images":"https://p1.meituan.net/210.0/wmproductdwm/aa40773ed7bccd77f93aa6e6d8b0c73a561494.jpg",
                    "price":"15.88",
                    "recommends_count":"7",
                    "sku_detail":[
                        {
                            "price":"15.88",
                            "sku_id":"944967552",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"尖椒炒蛋（不含米饭）",
                    "pid":"913274593",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/695cdacd599391097a187ddc580d25b7177213.jpg",
                    "price":"15.88",
                    "recommends_count":"10",
                    "sku_detail":[
                        {
                            "price":"15.88",
                            "sku_id":"992746429",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"小炒酸辣藕片（不含米饭）",
                    "pid":"1117395728",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/50ddd4d50643428ba05b3f82c1a815f0148980.jpg",
                    "price":"16.88",
                    "recommends_count":"4",
                    "sku_detail":[
                        {
                            "price":"16.88",
                            "sku_id":"1234472582",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"梅干菜炒豆角（不含米饭）",
                    "pid":"915055902",
                    "images":"https://p1.meituan.net/210.0/wmproductdwm/cb2027d2462f0bee808ea0375f6944b61445678.jpg",
                    "price":"16.88",
                    "recommends_count":"11",
                    "sku_detail":[
                        {
                            "price":"16.88",
                            "sku_id":"994712074",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"酱爆肉沫茄子（不含米饭）",
                    "pid":"891762162",
                    "images":"https://p0.meituan.net/210.0/wmproductdwm/8762b1623d5961d81c776a2b0e2997fd575655.jpg",
                    "price":"16.88",
                    "recommends_count":"14",
                    "sku_detail":[
                        {
                            "price":"16.88",
                            "sku_id":"969234267",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"火腿肠炒蛋（不含米饭）",
                    "pid":"1152092102",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/c6f15c2b032803b17c54ba3e76b3a537177631.jpg",
                    "price":"17.88",
                    "recommends_count":"7",
                    "sku_detail":[
                        {
                            "price":"17.88",
                            "sku_id":"1276180716",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"香菇炒肉（不含米饭）",
                    "pid":"1152078547",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/1bf24675dbd99d8c8cad2be8d9e7e85c171701.jpg",
                    "price":"20.88",
                    "recommends_count":"5",
                    "sku_detail":[
                        {
                            "price":"20.88",
                            "sku_id":"1276287046",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"农家笋干炒肉",
                    "pid":"870419136",
                    "images":"https://p0.meituan.net/210.0/wmproductdwm/176479050c9227a4dc8843148491af3b612911.jpg",
                    "price":"25.88",
                    "recommends_count":"1",
                    "sku_detail":[
                        {
                            "price":"25.88",
                            "sku_id":"944804947",
                            "sku":""
                        }
                    ]
                }
            ]
        },
        {
            "category":"特色干锅",
            "product":[
                {
                    "name":"鲜辣干锅鸡（微辣，不含米饭）",
                    "pid":"1226492750",
                    "images":"https://p1.meituan.net/210.0/wmproductdwm/2d59a07bb867d0d21d38cb931a732736336209.jpg",
                    "price":"36.88",
                    "recommends_count":"0",
                    "sku_detail":[
                        {
                            "price":"36.88",
                            "sku_id":"1365601470",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"招牌干锅肥肠（微辣，不含米饭）",
                    "pid":"1228096029",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/c632bf619b6af30f7e389b3e3e31186f209880.jpg",
                    "price":"36.88",
                    "recommends_count":"0",
                    "sku_detail":[
                        {
                            "price":"36.88",
                            "sku_id":"1367447870",
                            "sku":""
                        }
                    ]
                }
            ]
        },
        {
            "category":"清淡素菜",
            "product":[
                {
                    "name":"韭菜炒豆芽（不含米饭）",
                    "pid":"1153224010",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/1bb09b5cf54f54850d6452f9a64e5581160378.jpg",
                    "price":"11.88",
                    "recommends_count":"1",
                    "sku_detail":[
                        {
                            "price":"11.88",
                            "sku_id":"1277961968",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"小炒土豆片（不含米饭）",
                    "pid":"1145880556",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/78514c5f704f7e8c9177862ee0f999b4198276.jpg",
                    "price":"12.88",
                    "recommends_count":"9",
                    "sku_detail":[
                        {
                            "price":"12.88",
                            "sku_id":"1268067804",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"小炒手撕包菜（特价，不含米饭）",
                    "pid":"1126073642",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/7bd7b86f8f815b7c1238266c78b0d8f3130097.jpg",
                    "price":"12.88",
                    "recommends_count":"0",
                    "sku_detail":[
                        {
                            "price":"12.88",
                            "sku_id":"1244016401",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"酸辣大白菜（不含米饭）",
                    "pid":"1050389217",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/039fe135d4a9ca82c03ca8afb0bd4149147287.jpg",
                    "price":"12.88",
                    "recommends_count":"0",
                    "sku_detail":[
                        {
                            "price":"12.88",
                            "sku_id":"1157286948",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"小炒手撕包菜（不含米饭）",
                    "pid":"1023745410",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/e93bc244e1b25826aaf5be14bb462fa5160831.jpg",
                    "price":"12.88",
                    "recommends_count":"5",
                    "sku_detail":[
                        {
                            "price":"12.88",
                            "sku_id":"1126241146",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"清炒冬瓜（不含米饭）",
                    "pid":"1006873883",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/b848eb8a3c7b4cc5038473bd1129dff097186.jpg",
                    "price":"12.88",
                    "recommends_count":"1",
                    "sku_detail":[
                        {
                            "price":"12.88",
                            "sku_id":"1107466306",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"香菇炒青菜（不含米饭）",
                    "pid":"871735631",
                    "images":"https://p1.meituan.net/210.0/wmproductdwm/321082faab1188bccef8c83db0217f1e571304.jpg",
                    "price":"11.88",
                    "recommends_count":"5",
                    "sku_detail":[
                        {
                            "price":"11.88",
                            "sku_id":"946274298",
                            "sku":""
                        }
                    ]
                }
            ]
        },
        {
            "category":"爽口凉菜",
            "product":[
                {
                    "name":"松花皮蛋豆腐（不含米饭）",
                    "pid":"912482101",
                    "images":"https://p0.meituan.net/210.0/xianfu/91b91fcbc8683d32bf7eadca1123d5c9434176.jpg",
                    "price":"11.88",
                    "recommends_count":"2",
                    "sku_detail":[
                        {
                            "price":"11.88",
                            "sku_id":"991940662",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"糖拌西红柿（凉菜，不含米饭）",
                    "pid":"935003477",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/0a43cccc79c354edcc305a554bc717d5153510.jpg",
                    "price":"12.88",
                    "recommends_count":"0",
                    "sku_detail":[
                        {
                            "price":"12.88",
                            "sku_id":"1016509099",
                            "sku":""
                        }
                    ]
                }
            ]
        },
        {
            "category":"汤类",
            "product":[
                {
                    "name":"黑鱼骨豆腐汤（鲜美，不含米饭）",
                    "pid":"1239112675",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/ad82331d04aea942e44727f39ffe75a0125457.jpg",
                    "price":"15.88",
                    "recommends_count":"2",
                    "sku_detail":[
                        {
                            "price":"15.88",
                            "sku_id":"1379479163",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"鱼丸紫菜汤（不含米饭）",
                    "pid":"1185289151",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/30f6c6fc0d882844d39a6f66ec0f3e4888461.jpg",
                    "price":"10.88",
                    "recommends_count":"0",
                    "sku_detail":[
                        {
                            "price":"10.88",
                            "sku_id":"1316071990",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"冬瓜贡丸汤（不含米饭）",
                    "pid":"1172235223",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/8085cc679b42402576b9ffc5b69e76ec155346.jpg",
                    "price":"10.88",
                    "recommends_count":"2",
                    "sku_detail":[
                        {
                            "price":"10.88",
                            "sku_id":"1300641248",
                            "sku":""
                        }
                    ]
                }
            ]
        },
        {
            "category":"超值组合套餐",
            "product":[
                {
                    "name":"红烧带鱼+手撕包菜+米饭（一份）",
                    "pid":"1233408142",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/f1338d80e61fc20d3612a780d20e71cc178571.jpg",
                    "price":"35.88",
                    "recommends_count":"1",
                    "sku_detail":[
                        {
                            "price":"35.88",
                            "sku_id":"1373564618",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"香辣鸡腿+手撕包菜+米饭（一份）",
                    "pid":"1233641010",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/cb3971e18a01d2743448dba6ab87efc7189878.jpg",
                    "price":"36.88",
                    "recommends_count":"0",
                    "sku_detail":[
                        {
                            "price":"36.88",
                            "sku_id":"1373612666",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"农家小炒肉+手撕包菜+米饭（一份）",
                    "pid":"1233371633",
                    "images":"https://p0.meituan.net/210.0/xianfudwm/e4f1725d2025c4f23e876e46e8747b29161301.jpg",
                    "price":"37.88",
                    "recommends_count":"1",
                    "sku_detail":[
                        {
                            "price":"37.88",
                            "sku_id":"1373567688",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"爆炒肥肠+手撕包菜+米饭一份",
                    "pid":"1233422125",
                    "images":"https://p1.meituan.net/210.0/xianfudwm/8e647851e0d76cad574da96efc23ee9c183327.jpg",
                    "price":"38.88",
                    "recommends_count":"0",
                    "sku_detail":[
                        {
                            "price":"38.88",
                            "sku_id":"1373580209",
                            "sku":""
                        }
                    ]
                }
            ]
        },
        {
            "category":"开胃小菜",
            "product":[

            ]
        },
        {
            "category":"掌柜说",
            "product":[
                {
                    "name":"大堂实景",
                    "pid":"892440424",
                    "images":"https://p1.meituan.net/210.0/wmproduct/2a351eca79b4475530e99db51fded5f13396535.jpg",
                    "price":"0",
                    "recommends_count":"1",
                    "sku_detail":[
                        {
                            "price":"0",
                            "sku_id":"969986683",
                            "sku":""
                        }
                    ]
                },
                {
                    "name":"厨房实景",
                    "pid":"891781039",
                    "images":"https://p0.meituan.net/210.0/wmproduct/7064965d91cc02a8d32c9f1d0534d353604056.jpg",
                    "price":"0",
                    "recommends_count":"0",
                    "sku_detail":[
                        {
                            "price":"0",
                            "sku_id":"969197652",
                            "sku":""
                        }
                    ]
                }
            ]
        }
    ]
}
</script>
<style lang="less"> 
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
body {
  font-size: 63%;
}
html,
body,
#app {
  width: 100%;
  height: 100%;
}
#app {
  position:relative;
  header {
    height: 100px; 
    padding: 15px 10px 5px 10px;
    display:flex;
    background: rgba(41, 39, 39, 0.966);
    color: white;
    img {
        height: 70px;
        width:70px;
    }
  }
  .nav {
    
    display: flex;
    a {
      width: 60px;
      text-align: center;
      height: 2.5em;
      line-height: 2.5em;
      text-decoration: none;
      color:black;
    }
  }
}
#msg {
    padding:5px;
    p{
        margin: 3px;
    }
    //height:90px;
}
#atention {
    position: absolute;
    top:30px;
    right: 10px;
    width: 40px;
    padding:3px 0;
    border-radius: 5px;
    text-align: center;
    background: rgb(161, 161, 54);
    color: black;
}
</style>
